name: arfp-io
services:
  pages:
    # build: https://raw.githubusercontent.com/mdevoldere/edu-docker/develop/jekyll/Dockerfile
    build: .
    # image: mdevoldere-jekyll-develop
    container_name: arfpjekyll
    ports:
      - 4000:4000
      - 35729:35729
    networks:
    - default
    volumes:
      - ./docs:/srv/jekyll
    command: jekyll serve --force_polling --livereload
    